### ISSUE TITLE
\charscale bug

### ISSUE THREAD

**Issue by paly2** [RobtAll/novel#1]
Hello!

First of all, thank you very much for having made this document class and sharing it!

I've got a strange bug (not sure it's because of novel, though) with `\charscale` when containing a `\Ordinalstring` macro in french...

Here is a minimal example:
```latex
\documentclass{novel}
\usepackage{fmtcount}

\setdefaultlanguage{french}

\newcounter{Counter}

\begin{document}
	\stepcounter{Counter}
	\charscale[1]{\Ordinalstring{Counter}}
\end{document}
```
![2017-10-01-195035_568x150_scrot](https://user-images.githubusercontent.com/12398822/31057364-d6141c96-a6e1-11e7-8ccb-fafce4d87947.png)

The text in `\charscale` is shifted right, as you can see. The strangest thing is that if you put a second `\charscale` containing another `\Ordinalstring`, it will show exactly as it should. The bug does not appear when using english as language.

Do you see any possible cause for this ?

Thanks!

**Comment by RobtAll** [comment]
I'll have a look. It will take awhile, as I am in the middle of something else.

When used without an optional argument (or simply with scale 1), \charscale is an alias for \smash. So, if you see the same behavior using \smash instead of \charscale, then I will not be able to fix it.

However, if you see expected behavior with \smash, but not with \charscale, then there is a bug in my code.

**Comment by RobtAll** [comment]
The problem is with the `fmtcount` package, not `novel`. I will raise an issue with the maintainers of `fmtcount`.

Nature of the problem: `fmtcount` detects whether or not the compiler is xetex. If not, is defaults to pdftex. However, `novel` uses luatex. Since luatex is not xetex, `fmtcount` defaults to pdftex, and treats strings using babel (wrong) instead of polyglossia.

The solution is to modify `fmtcount.sty` so that it detects luatex, and fork the logic accordingly.

TEMPORARY SOLUTION : Probably will continue to work in the long term. In your Preamble, tell a lie to `fmtcount` :

    \usepackage{ifxetex}
    \xetextrue
    \usepackage{fmtcount}
    \xetexfalse

**Comment by paly2** [comment]
Thank you very much for your attempt to fix the problem, but it doesn't seem to work. I added your code in my Preample and the text is still shifted right.

However I tested with `\smash` and the bug also appears, so don't reopen this issue ;-)

**Comment by RobtAll** [comment]
I have raised the issue with fmtcount. Apparently, \xetextrue does not address every situation.

**Comment by RobtAll** [comment]
Please test the attached fmtcount-faux.sty file. Unzip it, and place
fmtcount-faux.sty in your texmf-local directory, probably in
(texmf-local)/tex/latex/fmtcount-faux (new directory). Then update file
names, using mktexlsr or MikTeX FNDB.

In your TeX document, instead of \usepackage{fmtcount}  request
\usepackage{fmtcount-faux}.

The language definitions will be read from fmtcount. The only thing I have
changed is the logic for calling either polyglossia or babel, depending on
whether you are compiling with luatex. Novel class always uses luatex.

This definitely works for me, using TeXlive 2017.

Je peux lire français.

Regards,
Robert Allgeyer

**Comment by paly2** [comment]
Thanks, but files sent by e-mail are not downloadable from GitHub. It is possible to attach files from the GitHub Web interface by dragging & dropping them.

**Comment by RobtAll** [comment]
File fmtcount-faux.sty is now in the "extras" folder of my GitHub project.
You may download it from there.

IMPORTANT: You must \setdefaultlanguage BEFORE \usepackage{fmtcount-faux}.
If you do not write the commands in this order, then the fix will not work.
Your example code (issue) has the commands in reverse order.

Place fmtcount-faux.sty in (texmf-local)/tex/latex/fmtcount-faux then
update your file name database.

- R. A.

**Comment by RobtAll** [comment]
Issue: Incorrect placement of `\Ordinalstring` (package `fmtcount`).

This issue is caused by failure to detect luatex in `fmtcount`, not by `novel`. The `fmtcount` package maintainers have been informed. Until such time as `fmtcount` is updated with the fix, you may install a temporary fix:

(1) Download file `fmtcount-faux.sty` from the "extras" folder of the novel GitHub project page.

(2) In your `texmf-local` directory, create folder `tex/latex/fmtcount-faux` and place the `fmtcount-faux.sty` file in there.

(3) Update you file name database, either using `mktexlsr` or MikTeX Update FNDB, as appropriate.

(4) In your TeX document, change `\usepackage{fmtcount}` to `\usepackage{fmtcount-faux}`.

(5) In your TeX document, place `\setdefaultlanguage` BEFORE `\usepackage{fmtcount-faux}`. If you write these commands in the wrong order, then the fix will not work. This will probably also be true when you later revert to `fmtcount`.

**Comment by paly2** [comment]
Thank you so much, it works perfectly! Your previous fix using `ifxetex`, also works if I place `\setdefaultlanguage` before `\usepackage{fmtcount}`

**Comment by RobtAll** [comment]
The `fmtcount` package has been updated (now on CTAN) with the required internal fix.
