### ISSUE TITLE
How to accomplish full-page illustrations?

### ISSUE THREAD

**Issue by inklesspen** [RobtAll/novel#3]
I want to insert some interior full-page illustrations in the novel I'm laying out. In normal LaTeX, I'd define a float for this purpose, but `novel` blocks the `float` package.

So far, the best solution I can find is to compile the PDF without the images, then manually pick a place to insert a page, break the paragraph in two, and add a `\BlockImage` wrapped in `\clearpage`s. Is there any better option?

**Comment by RobtAll** [comment]
If by "full page" you mean reaching the page edges, so that bleed is necessary: That cannot be done in novel class. This is by intent, since there would be other considerations, especially if the book will go to a print-on-demand service. Only a cover image can be done that way.

But if by "full page" you mean entirely filling the area all the way to the ordinary margins, that is easily done without using float.

If your global page layout uses header and/or footer, and you want the image to have its top where the first line of main body text would be: Use `\noindent\InlineImage` to place the image at the begiining of the text block. Its top will sit at the text baseline there. If you want its top to be the highest possible (while still in main text block) then vertically offset by 1em.

If you want the image to have its top at the top of the header: Do the above, but this time vertically offset the image by the head jump (which is the distance from baseline of fisrt main text, up to the baseline of header text), plus 1em. So, let's say that your head jump is 1.5 (default). The code for normal baselineskip is `\nbs` and the code for normal font size (em) is `\nfs`. You could offset the image by `1.5\nbs+\nfs`.

Every print service specifies a "safe area" which pertains to the minimum allowed margins. Most books have wider margins. You can occupy the entire safe area (if you know its size) by horizontal and vertical offset of the image.

It can be done. I have done it during code testing.

Remember that you cannot scale or crop the image within novel class. You must prepare the image at exact size and resolution. Again, this is by intent.

Incidentally: Do not use this git repository for a production book. I have experimental code here, which changes many things, has not been fully tested, and is ahead of the documentation.

**Comment by inklesspen** [comment]
Thank you, but I think perhaps I have not properly explained my question.

Suppose that I want to put an illustration within Chapter 3 of my exciting novel, perhaps immediately after page 50. The problem is that a paragraph at the bottom of the page is split between page 50 and 51; this happens often in books. If I were using a different LaTeX class, I could place a float at the point in the text which corresponds to the illustration, telling LaTeX to place the image taking up the entire the following page, such that the paragraph is split over pages 50 and 52, with the illustration on 51.

Since novel doesn’t support floats, this solution is unavailable to me. Do you know of something equivalent that novel does support?

**Comment by inklesspen** [comment]
Nevermind; when I originally read your reply, somehow I missed the first two paragraphs.

**Comment by RobtAll** [comment]
You didn't miss them; I added them by way of edit. You must have read the un-edited reply first.

For the specific case you mentioned, you can do it this way without float: Make a preliminary run, then note where the paragraph breaks at the end of page 50. Insert `\linebreak` there. Place the `InlineImage` which will appear on page 51. It is still part of the same paragraph. Then the text of the paragraph will resume after the image (if necessary, use `\\` to force it).

The catch: If you subsequently edit your work, and the paragraph does not break in the same place, then you will have to re-work placement. That's where float would be useful. But if not carefully done, a float (in the context of fiction writing) is likely to be very disruptive.

**Comment by RobtAll** [comment]
Further info: Merely using `unblock` in the class options probably will not be enough. The reason is that novel does not have a pre-defined figure environment (unlike article class, for example).

For now, you can unblock and use the `newfloa` package, which allows you to define your own floating environment, via the `\DeclareFloatingEnvironment` command. It is not as difficult as it sounds. Maybe I'll have a look at that, and work it into a future version.

The main issue with floats of any kind, is ensuring that the following text is on-grid. I imagine that's won't be a problem for full-page floats (but you never know, with TeX).

**Comment by RobtAll** [comment]
I'm interested in learning what you find.

In the intervening time, I tried `newfloat` and `DeclareFloatingEnvironment`. Alas, it exhibits all of the problems for which I block floats in the first place. They can be manually fixed, but a lot of code-ripping is involved.

The essence of the problem is that TeX does not respect grid typesetting by default. And, even though various glue values can be set to zero, numerous packages re-set them, causing baseline skips to be too small or too large when you enter or exit boxes and environments. In its essential code, novel spends a lot of time removing TeX behavior, rather than adding to it.

In the case at hand, the floated material will appear too high on its page, because its container does not respect vertical position according to line grid. It merely places the top of the material wherever it can go, without clashing with something else. Worse, if the material is not full-page, the following material resumes with an odd line gap afterward, and it is very difficult to fix,

For a full-page image, the top can be adjusted via offset, and hopefully there is no following material on the same page. But this is not much of an improvement. The sure-fire method is to do what I suggested earlier: Make a preliminary run, and use `\linebreak`.

**Comment by RobtAll** [comment]
Aha! This may be simpler than I previously thought. It won't address every situation, but I think it will address your specific question.

You do not need to use `unblock` in the class options, and you do not need to load the `float` or `newfloat` package. Apparently there is a built-in structure that can be used directly.

In Preamble:

    \makeatletter
    \newenvironment{fakefigure}
               {\@float{figure}[!h]}
               {\end@float\par}
    \makeatother

You can use something other than [!h] as needed.

In document body:

    \begin{fakefigure}
    ... content
    \end{fakefigure}

The content does not need to be an image.

In quick testing, the floated content appears in a predictable location at the top of its page. Can still be adjusted using image offset, if you prefer.

If there is following content on the same page, there may be a line gap problem, which will throw the following text off grid. Perhaps that can be addressed. I'll think about it, but don't expect a quick solution.

**Comment by RobtAll** [comment]
I deleted a lengthy comment from 3 hours ago, as it did not hold up under testing. So I will try again. This does not need `unblock` class option, and does not need `float` package:

In Preamble:

    \makeatletter
    \gdef\ftype@figure{0}
    \gsetlength\intextsep{0pt}
    \gsetlength\textfloatsep{0pt}
    \gsetlength\floatsep{0pt}
    \newenvironment{fakefigure}[1]{%
    \@float{figure}[!ht]%
    \begin{linegap}{#1}%
    }{%
    \end{linegap}%
    \end@float\par%
    } %
    \makeatother

In document body:

     \begin{fakefigure}{10} % Number of vertical lines sufficient to enclose image, whatever integer works.
    \BlockImage[c,0pt,\nfs]{yourimage.png} % Not necessarily \nfs, depending on how you like it.
    \end{fakefigure}

This appear to be satisfactory for images. Further testing required.

**Comment by RobtAll** [comment]
After many tries, I decided that simplest was best. When the next release comes out (maybe end of January 2018), the \BlockImage command will no longer be available. Actually, it will still exist and can be used, but its description will be removed from the documentation, and usage discouraged. Most of the issues concern the ability to "accompany" text with the image. That causes the TeX layout engine to do some strange things, all for a feature that will hardly ever be used. If you need text in the same block as the image, then make the image larger and include the raster text.

Substitute command, which perform the float, as originally requested on this thread:

    %% EXPERIMENTAL. Subject to revision before release:
    % New in v.1.48. \FloatImage. Will always be centered.
    % \FloatImage[xoffset,yoffset]{yourimagename.png} % or jpg
    % This is a substitute for other floats. Does not require `float' package.
    \setlength\floatsep{0pt}
    \setlength\textfloatsep{0pt}
    \setlength\dbltextfloatsep{0pt}
    \setlength\intextsep{0pt}
    \gdef\ftype@figure{1}
    \ExplSyntaxOn
    \DeclareDocumentCommand \FloatImage { O{} m } {%
      \@float{figure}[!ht]%
      \BlockImage[c,#1]{#2}% do not call this command directly
      \end@float\par%
    } % end \FloatImage
    \ExplSyntaxOff
    %%

You can try that now. Place it in Preamble, wrapped by `\makeatletter` and `\makeatother`.

Note that `\FloatImage` does not offer the option of left-center-right alignment. It will always be centered horizontally. There is a good reason for that. If you need the image to the side, then simply make a larger image at full text width, with white area.

The xoffset and yoffset will reposition the image relative to its standard location. In many cases, a good choice is `[0pt,\nfs]` where `\nfs` is novel's own code for 1em in the normal font.

`\FloatImage` always uses the `!ht` float positioning, which is surely the only kind that would ever be used in the context of a novel. By limiting the choice, there are fewer potential issues.

If you need to float something other than an image... Out of luck. But you can always create the object (perhaps a table) in another document class, and make an image from its PDF page. For that, you would not directly insert PDF; you need a graphics program to create png or jpg.

**Comment by RobtAll** [comment]
An improved version of the above has been pushed here. It is file `novel-Images.sty` version 1.46.5t. If you wish, download it (don't clone everything) and place it in your texmf-local directory.

It contains a new macro `\FloatImage[xoffset,yoffset]{imagename.png}` or jpg.

I believe this will do what you originally asked. Feedback encouraged.

If the floated image cannot fit where it is written, then it will appear at the top of the following page, with the usual continuity of text. Unlike usual TeX behavior, if the image is too tall for the available textblock, it will not be pushed to later; it will remain on that page and overflow the bottom. I believe this is better behavior.

The image will always be horizontally centered. If that's not what you want, then you can either create a wider image with white space, or use the xoffset (more than you think due to centering).

Unlike `\BlockImage` the floated image cannot have accompanying text in the same block. If that's what you need, then build it into the image.

I expect that `\BlockImage` is obsolescent. Always was a bit hard to handle.

**Comment by inklesspen** [comment]
I still haven’t had a chance to try it, but thanks for all your advice. I will make sure to report back once I do.

**Comment by RobtAll** [comment]
Version 1.50pre1, now available for testing, has some float capability added. Should do full page floats well. You can download the zip archive at GitHub, and try it in texmf-local.
